spring.application.name=springBoot2

spring.datasource.url=jdbc:mysql://localhost:3306/springboot2
spring.datasource.username=root
spring.datasource.password=Woal9256!
spring.jpa.hibernate.ddl-auto=update